config/routes.rb
Rails.application.routes.draw do
  # get 'appointments/index'
  # get 'appointments/new'
  # get 'doctors/index'
  # get 'doctors/show'
  # get 'doctors/new'
  # get 'patients/index'
  # get 'patients/show'
  # get 'patients/new'

  root 'doctors#index'

  resources :patients
  resources :doctors do
    resources :appointments, only: [:index, :new, :create, :destroy] # the only: has something to do with rails/info/routes in localhost (I think)
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointments

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
  # defining our full_name method for our show methods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @doctor = Doctor.find(params[:doctor_id])
    @xrays = @doctor.appointments.where(role: 'xrays')
    @colds = @doctor.appointments.where(role: 'colds')
    @diseases = @doctor.appointments.where(role: 'disease')
      # here we're giving the Appointments controller access to all of the doctor info, patient info, and specialties.
  end

  def new
    @doctor = Doctor.find(params[:doctor_id]) # you have to do :doctor_id instead of just :id... dunno why but that's what the routes say
    @patients = Patient.all - @doctor.patients # this is to subtract patients that already have appts so we can get appts for the others
    @appointment = Appointment.new
    # a problem I found is that while making appointments for a single doctor I can subtract the patients from who's already scheduled, but
      # if I go to a new doctor then it resets? How do I fix this? maybe I can - @Doctor.all.patients??? instead of @doctor.patients. NO this doesn;t work. Let's figure it out.
    
      # what if I make an array that, everytime you create an appointment it pushes that patient into an array which I would subtract from my @patients method? Then with the
        # delete method I could make a way to pop or delete that patient from the array?
         def list_patients 
          @patients.collect{ |p| [p.full_name, p.id]} 
        end 
  end

  def create
    # binding.pry  for testing
    @doctor = Doctor.find(params[:doctor_id])
    @doctor.appointments.create(appointments_params) # go define this. don't forget
      if @doctor.save
        redirect_to doctor_appointments_path(@doctor) 
        # if it saves it'll go to doctors/appointments (I think) and show that doctors appoitments, including the one you just created
      else
        render :new
      end
  end

  def destroy
    @doctor = Doctor.find(params[:doctor_id])
    @doctor.appointments.find(params[:id]).destroy
    redirect_to doctor_appointments_path(@doctor)
  end

  private

  def appointments_params
    params.require(:appointment).permit(:patient_id, :role)
  end
end

# let's make that array here
# booked_patients = []

# what if I can make a method that will do a loop to search for all doctors that exist, and if Doctor.find(a number in the loop) == nil it'll move on until it finds
# doctors that DO exist. If they exist then it'll

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
        # same concept/thing as the patients controller. Is it the same or different fror the appointments controller? .. I'll find out later when I do it.
  def index
    @doctors = Doctor.all
  end

  def show
    @doctor = Doctor.find(params[:id])
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to @doctor
    else
      render :new
    end
  end

  def destroy
    @doctor = Doctor.find(params[:id])
    @doctor.destroy
    redirect_to doctors_path
  end

  private

  def doctor_params
    params.require(:doctor).permit(:name)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  
  def index
    @patients = Patient.all
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to @patient
    else
      render :new
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy
    redirect_to patients_path 
    # when it's destroyed instead of redirecting you to that patient (since s/he is gone) like in the create method, this'll take you back to
    # the list of all the patients
  end

  private

  def patient_params
    params.require(:patient).permit(:first_name, :last_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/index.html.erb
        <h1><%= @doctor.name %>: Appointments</h1>
      <%= link_to 'Make an appointment', new_doctor_appointment_path(@doctor) %>
      <hr />


                                <!-- instead of doing xray/cold/disease.patient.full_name, I think I need to do role.doctor.name -->
      <h2>Xrays</h2>
      <ul>
        <% @xrays.each do |xray| %>
          <li>
            <%= xray.patient.full_name %>
            <br />
            <%= link_to 'Cancel', doctor_appointment_path(@doctor, xray), method: :delete %>
            <br/>
          </li>
        <% end %>
      </ul>
      <h2>Colds</h2>
      <ul>
        <% @colds.each do |cold| %>
          <li>
            <%= cold.patient.full_name %>
            <br />
            <%= link_to 'Cancel', doctor_appointment_path(@doctor, cold), method: :delete %>
            <br/>
          </li>
      <% end %>
      </ul>
      <h2>Diseases</h2>
      <ul>
        <% @diseases.each do |disease| %>
          <li>
            <%= disease.patient.full_name %>
            <br />
            <%= link_to 'Cancel', doctor_appointment_path(@doctor, disease), method: :delete %>
            <br/>
        </li>
      <% end %>
      </ul>

app/views/appointments/new.html.erb
<%= form_with( model: [@doctor, @appointment], local:true) do |f| %>
  <%= f.label :patient %>
  <%= f.select :patient_id, @patients.collect{ |p| [p.full_name, p.id]} %>
  <%= f.label :role %>
  <%= f.select :role, ['xrays','colds','disease'] %>
  <br />
  <%= f.submit %>
<% end %>

<!-- 
    <% def list_patients %>
      <% @patients.collect{ |p| [p.full_name, p.id]} %>
    <% end %>
  -->

app/views/doctors/index.html.erb
<h1>Doctors</h1>
        <%= link_to 'Add Doctor', new_doctor_path %>
        <hr />
        <h2><%= @doctors.length <= 0 ? "No Doctors!" : "" %></h2>  <!-- I thought it was cool when James did it. Don't think I'll ever not have doctors 
                                                                      in my list lol but nice to remember, and to practice using a ternary, so I'll use it here. -->
        <ul>
          <% @doctors.each do |doctor| %>
            <li>
              <%= link_to doctor.name, doctor %>
            </li>
          <% end %>
        </ul>

app/views/doctors/new.html.erb
<h1>Add a Doctor</h1>
  <%= form_with(model: @doctor, local: true) do |f|  %>
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
    <%= f.submit %>
  <% end %>
  <!-- standard form. :D remember that error I had before though!!! Don't use an echo tag for 'end'. -->

app/views/doctors/show.html.erb
<h1><%= @doctor.name %></h1>
      <hr />
      <br />
      <%= link_to 'Appointments', doctor_appointments_path(@doctor) %>
      <br />
      <br />
      <br />
      <%= link_to "Delete Doctor", @doctor, method: :delete %> <!-- reminder to self that if I don't add this method: :delete, then it'll run as the show method. -->

      <!-- ------------------------------------------------------------------------------------------------------------------------ -->
      <!-- QUESTION for later. Why can I simply put @doctor, instead of like doctors_path? How does this work and why is it used??? -->
      <!-- ------------------------------------------------------------------------------------------------------------------------ -->

app/views/layouts/_navbar.html.erb
<nav>
    <%= link_to 'Doctors', doctors_path %> ~
    <%= link_to 'Patients', patients_path %>
    <hr/>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorsAppointments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>  <!-- if I don't put _navbar.html.erb, how does it know what I'm talking about? -->
    <%= yield %>
          <!-- I believe that any text or links I put UNDER 'yield' will ONLY show up on the root page. I could be wrong though. 
                Food for thought - what could that be useful for? -->
  </body>
</html>

app/views/patients/index.html.erb
<h1>Patients</h1>
      <%= link_to 'Add Patient', new_patient_path %>
      <hr />
      <ul>
        <% @patients.each do |patient| %>
          <li>
            <%= link_to patient.full_name, patient %> 
  <!--  define full_name in the Patients model, to be able to call it here -->
          </li>
      <% end %>
      </ul>

app/views/patients/new.html.erb
<h1>Add a Patient</h1>
     <%= form_with(model: @patient, local: true) do |f| %>  <!-- Honestly i don't understand why this form is the way it is, but I know this is
                                                              the correct way of doing it and that I'll understand it better with more time and experience -->

        <%= f.label :first_name %>
        <%= f.text_field :first_name, required: true, autofocus: true, placeholder: "First Name" %> <!-- note to myself to remember the placeholder thing that
                                                                                                      James reminded me of today. will be useful in future  -->

        <%= f.label :last_name %>
        <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>

        <%= f.submit %>  
    <% end %>  <!-- Simon helped me catch this mistake - I had done an echo tag <%= (with equals) instead of the normal tag on 'end' and it was throwing and error
                    so remember to watch for things like this. Simon if you read this, thanks :D haha  -->

app/views/patients/show.html.erb
<h1><%= @patient.full_name %></h1> <!-- again, I defined this full_name in class Patient < ApplicationRecord so I can call it here -->
      <hr />
      <h2>Doctors</h2>
      <h4>--click on your doctor to see your appointments, or go make an appointment if you don't have one yet--</h4>
      <ul>
        <% @patient.doctors.each do |doctor| %>
          <li>
            <%= link_to doctor.name, doctor %>
          </li>
        <% end %>
      </ul>
      <br />
      <br />
      <br />
      <%= link_to 'Delete Patient', @patient, method: :delete %>

      <!-- make a way to list each appointment for the patient along with the doctor that it's with -->